# -*- coding: utf-8 -*-
"""Hola-Mundo-en-Colab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U0sBb17ExOsSEa9aHWc4ifw_65L314cl

Primer codigo: "Hola Mundo"
"""

print("Hola, este es mi primer programa en Python")

