# -*- coding: utf-8 -*-
"""Variables.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LyW_5NaHNB_RNtOWsQKm8-s9KzXnsUJa
"""

nombre = input("Ingrese su Nombre:")
edad = int(input("Ingrese su edad:"))
print("Hola "+nombre+", tienes: "+ str(edad) +" años")

"""Impresion de variables"""